### ISSUE TITLE
Put secret variables in .env file

### ISSUE THREAD

**Issue by wendelfreitas** [mateusmlsv/gobarber-rocketseat#1]
https://github.com/mateusmlsv/gobarber-rocketseat/blob/b448f91d3ddc973e39cc7d62122e7b50ec02e304/src/config/auth.js#L2

You should maintain secret variables out of your source code try to work with **.env**ironment variables.

If you need, I can help you with this.

**Comment by mateusmlsv** [comment]
So helpe me, please!!

**Comment by wendelfreitas** [comment]
You need to install [Dotenv](https://www.npmjs.com/package/dotenv) if you are using npm, just do `npm install dotnev`. After this, create `.env` file in your root folder then you create your variable and set value for her.

Example: 
`APP_AUTH_SECRET=f29618255c309de4469993cce24286ea`;

After this, you need to import that variable in your file.

First import the package in your file (SessionController.js for example)

`require('dotenv').config();`

Then, get the variable from **.env** file.

`const { APP_AUTH_SECRET} = process.env;`

Now you can use the `APP_AUTH_SECRET`, but remember, the **.env** file should stay in your `.gitignore`

**Comment by gamaralm** [comment]
It's also a good practice to keep an `.env.example` file in your repository with the same settings as the `.env` file, but with no values.

**Comment by mateusmlsv** [comment]
Guys, I'm using <code>yarn</code>, can you help me with this??

**Comment by wendelfreitas** [comment]
@mateusmlsv just do `yarn add dotenv` instead `npm install dotenv`
